#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import json
import logging
import os
import os.path as osp
import re
import sys
import time
import traceback
from collections import defaultdict
from datetime import datetime

import torch
import torch.distributed as dist
from decord import VideoReader
from tqdm import tqdm
from transformers import AutoProcessor
from transformers.utils import is_flash_attn_2_available

try:
    sys.path.append(osp.abspath(osp.join(osp.dirname(__file__), '..')))
    from modeling_qwen2_vl import Qwen2VLForConditionalGeneration
    from qwen_vl_utils import process_vision_info
except ImportError as e:
    print(f"Import failed: {e}")
    print("Please ensure 'modeling_qwen2_vl.py' and 'qwen_vl_utils.py' are in your PYTHONPATH, and that all related dependencies are installed.")
    sys.exit(1)

MODEL_PATH = "Qwen/Qwen2.5-VL-7B-Instruct" 
TASK_JSON = "/path/to/your/mlvu/dev_debug_mc.json"
VIDEO_DIR = "/path/to/your/mlvu/root/"
RESULT_DIR = "eval_results/mlvu"
N_FRAMES = 768  
MIN_FRAMES = 8
MAX_FRAMES = 768 

PROMPT_TEMPLATE = """Select the best answer to the following multiple-choice question based on the video. Respond with only the letter (A, B, C, D, etc.) of the correct option.
Question: {}
Options:
{}
The best answer is:"""

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
fmt_str = "%(asctime)s %(levelname)5s | %(message)s"
fmt = logging.Formatter(fmt_str)

def extract_answer_letter(s: str) -> str:
    """Robustly extract answer option letter from model response"""
    s = s.strip()
    answer_prefixes = [
        "The best answer is", "The correct answer is", "The answer is", "The answer",
        "The best option is", "The correct option is", "Best answer:", "Best option:",
    ]
    for prefix in answer_prefixes:
        if s.lower().startswith(prefix.lower()):
            s = s[len(prefix):].strip()
            break

    matches = re.search(r"^\(?([A-E])\)?\.?\b", s, re.IGNORECASE)
    if matches:
        return matches.group(1).upper()

    matches = re.search(r"\b([A-E])\b", s, re.IGNORECASE)
    if matches:
        return matches.group(1).upper()
        
    return ""


def merge_jsonl_files(base_path, world_size):
    """Merge jsonl files generated by all ranks"""
    merged_data = []
    for rank in range(world_size):
        file_path = f"{base_path}_rank{rank}.jsonl"
        if osp.exists(file_path):
            with open(file_path, 'r', encoding='utf-8') as f:
                for line in f:
                    try:
                        merged_data.append(json.loads(line))
                    except json.JSONDecodeError:
                        logger.warning(
                            f"Failed to parse line in file {file_path}: {line.strip()}")

    merged_file_path = f"{base_path}_merged.jsonl"
    with open(merged_file_path, 'w', encoding='utf-8') as f:
        for item in merged_data:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
    logger.info(f"Successfully merged {len(merged_data)} records to {merged_file_path}")
    return merged_file_path


def main():
    parser = argparse.ArgumentParser(description="Distributed evaluation script for MLVU dataset.")
    parser.add_argument("--model_path", type=str, default=MODEL_PATH, help="Path to model weights (local or Hugging Face Hub)")
    parser.add_argument("--task_json", type=str, default=TASK_JSON, help="Path to MLVU task JSON file")
    parser.add_argument("--video_dir", type=str, default=VIDEO_DIR, help="Root directory containing video files")
    parser.add_argument("--result_dir", type=str, default=RESULT_DIR, help="Directory for storing results, logs, and outputs")
    parser.add_argument("--run_name", type=str, default="mlvu_eval_run", help="Name of this run, used for generating filenames")
    parser.add_argument("--n_frames", type=int, default=N_FRAMES, help="Target number of frames to sample per video")
    parser.add_argument("--min_frames", type=int, default=MIN_FRAMES, help="Minimum number of frames for video processing")
    parser.add_argument("--max_frames", type=int, default=MAX_FRAMES, help="Maximum number of frames for video processing")
    parser.add_argument("--max_new_tokens", type=int, default=128, help="Maximum number of new tokens to generate")
    args = parser.parse_args()

    # Distributed Environment Initialization
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    torch.cuda.set_device(local_rank)
    dist.init_process_group(backend='nccl')
    world_size = dist.get_world_size()
    is_main_process = local_rank == 0

    # Path and Logging Configuration
    curr_time = datetime.now().strftime("%Y%m%d_%H%M%S")
    if is_main_process:
        os.makedirs(osp.join(args.result_dir, 'output'), exist_ok=True)
        os.makedirs(osp.join(args.result_dir, 'log'), exist_ok=True)
    dist.barrier()
    
    log_path = osp.join(args.result_dir, 'log', f"{args.run_name}_{curr_time}_rank{local_rank}.log")
    output_jsonl_path = osp.join(args.result_dir, 'output', f"{args.run_name}_{curr_time}_rank{local_rank}.jsonl")
    
    file_handler = logging.FileHandler(log_path)
    file_handler.setFormatter(fmt)
    logger.addHandler(file_handler)
    if is_main_process:
        stream_handler = logging.StreamHandler(sys.stdout)
        stream_handler.setFormatter(fmt)
        logger.addHandler(stream_handler)
    
    logger.info(f"--- [Rank {local_rank}/{world_size}] Process started ---")
    logger.info(f"Run configuration: {vars(args)}")

    # Model and Preprocessor Loading
    torch.manual_seed(1234)
    if not is_flash_attn_2_available():
        logger.warning("Flash Attention 2 is not available. Falling back to SDPA. Performance may be affected.")
        attn_implementation = "sdpa"
    else:
        attn_implementation = "flash_attention_2"
        logger.info("Flash Attention 2 is available and will be used for acceleration.")
    
    if not is_main_process:
        dist.barrier()  
    
    logger.info(f"[Rank {local_rank}] Starting to load model: {args.model_path}")
    model = Qwen2VLForConditionalGeneration.from_pretrained(
        args.model_path,
        torch_dtype=torch.bfloat16,
        device_map=f"cuda:{local_rank}",
        attn_implementation="sdpa",
    )
    processor = AutoProcessor.from_pretrained(args.model_path)
    
    if is_main_process:
        dist.barrier() 
    logger.info(f"[Rank {local_rank}] Model and preprocessor loaded successfully.")

    # Data Loading and Distributed Splitting
    if not osp.exists(args.task_json):
        logger.error(f"Task file not found: {args.task_json}")
        sys.exit(1)
        
    with open(args.task_json, 'r', encoding='utf-8') as f:
        full_data = json.load(f)

    all_questions = []
    for video_info in full_data:
        for i, conv in enumerate(video_info['conversations']):
            question_id = f"{video_info['video_id']}_q{i}"
            all_questions.append({
                'video_id': video_info['video_id'],
                'video_path': video_info['video_path'],
                'question': conv['question'],
                'choices': conv['choices'],
                'answer': conv['answer'],
                'question_type': conv['question_type'],
                'question_id': question_id,
            })

    num_samples = len(all_questions)
    rank_indices = list(range(num_samples))[local_rank::world_size]
    task_data = [all_questions[i] for i in rank_indices]
    logger.info(f"[Rank {local_rank}] Data flattening and splitting complete. This process will handle {len(task_data)} / {num_samples} questions.")

    processed_ids = set()
    if osp.exists(output_jsonl_path):
        with open(output_jsonl_path, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    processed_ids.add(json.loads(line)['question_id'])
                except (json.JSONDecodeError, KeyError):
                    continue
    if processed_ids:
        original_count = len(task_data)
        task_data = [item for item in task_data if item['question_id'] not in processed_ids]
        logger.info(f"[Rank {local_rank}] Resuming progress from existing output file. Skipped {original_count - len(task_data)} completed tasks.")

    start_time = time.time()
    cnt_total = defaultdict(int)
    cnt_correct = defaultdict(int)
    progress_bar = tqdm(task_data, total=len(task_data), disable=not is_main_process, desc=f"Rank {local_rank} Inference")

    for item in progress_bar:
        try:
            video_path = osp.join(args.video_dir, item['video_path'])
            if not osp.exists(video_path):
                logger.warning(f"Video file not found: {video_path}, skipping question {item['question_id']}")
                continue

            # Dynamically adjust sampled frame count
            try:
                vr = VideoReader(video_path)
                video_frame_count = len(vr)
            except Exception as e:
                logger.error(f"Failed to read video {video_path} with decord. Skipping. Error: {e}")
                traceback.print_exc()
                continue
            
            final_nframes = max(args.min_frames, min(args.n_frames, video_frame_count))

            options_str = "\n".join([f"{chr(65+i)}) {choice}" for i, choice in enumerate(item['choices'])])
            query = PROMPT_TEMPLATE.format(item['question'], options_str)
            
            messages = [{"role": "user", "content": [
                {"type": "video", "video": f"file://{osp.abspath(video_path)}", "nframes": final_nframes, "max_frames": args.max_frames},
                {"type": "text", "text": query}
            ]}]

            text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            
            patch_size = model.config.vision_config.patch_size
            image_inputs, video_inputs = process_vision_info(messages, image_patch_size=patch_size)

            inputs = processor(
                text=[text],
                images=image_inputs,
                videos=video_inputs,
                padding=True,
                return_tensors="pt"
            ).to(model.device)

            gen_kwargs = {"max_new_tokens": args.max_new_tokens, "do_sample": False}
            generated_ids = model.generate(**inputs, **gen_kwargs)
            generated_ids_trimmed = generated_ids[:, inputs['input_ids'].shape[1]:]
            response = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True)[0]

            try:
                answer_idx = item['choices'].index(item['answer'])
                correct_letter = chr(65 + answer_idx)
            except ValueError:
                logger.error(f"[Rank {local_rank}] Critical error processing {item.get('question_id', 'N/A')}: {e}")
                continue

            pred_letter = extract_answer_letter(response)
            is_correct = (pred_letter == correct_letter)
            question_type = item['question_type']
            
            if is_correct:
                cnt_correct['overall'] += 1
                cnt_correct[question_type] += 1
            cnt_total['overall'] += 1
            cnt_total[question_type] += 1

            output_dict = {
                'question_id': item['question_id'], 'video_id': item['video_id'],
                'question_type': question_type, 'question': item['question'], 'choices': item['choices'],
                'answer': item['answer'], 'correct_letter': correct_letter,
                'response': response, 'prediction': pred_letter, 'is_correct': is_correct,
            }
            with open(output_jsonl_path, 'a', encoding='utf-8') as f:
                f.write(json.dumps(output_dict, ensure_ascii=False) + '\n')

        except Exception as e:
            logger.error(f"[Rank {local_rank}] 处理 {item.get('question_id', 'N/A')} 时发生严重错误: {e}")
            traceback.print_exc()

    # Result Aggregation and Cleanup
    dist.barrier()
    logger.info(f"[Rank {local_rank}] Inference complete. Waiting for all processes and starting aggregation...")
    
    # Collect all possible question types
    all_question_types = sorted(list(set(q['question_type'] for q in all_questions)))
    
    # Place this process's statistics into a Tensor
    stats_list = [cnt_total['overall'], cnt_correct['overall']]
    for q_type in all_question_types:
        stats_list.extend([cnt_total[q_type], cnt_correct[q_type]])
    stats_tensor = torch.tensor(stats_list, dtype=torch.long, device=f'cuda:{local_rank}')
    
    dist.all_reduce(stats_tensor, op=dist.ReduceOp.SUM)

    if is_main_process:
        base_output_path = osp.join(args.result_dir, 'output', f"{args.run_name}_{curr_time}")
        merge_jsonl_files(base_output_path, world_size)

        total_processed = stats_tensor[0].item()
        total_correct = stats_tensor[1].item()
        
        if total_processed == 0:
            logger.info("No questions were successfully processed by any process.")
        else:
            accuracy = 100 * total_correct / total_processed
            logger.info(f"[Overall Results]: Total={total_processed}, Correct={total_correct}, Accuracy={accuracy:.2f}%")

        logger.info("--- Accuracy by Question Type ---")
        for i, q_type in enumerate(all_question_types):
            total_cat = stats_tensor[2 + i*2].item()
            correct_cat = stats_tensor[3 + i*2].item()
            if total_cat > 0:
                acc_cat = 100 * correct_cat / total_cat
                logger.info(f"  - {q_type:<25}: {correct_cat}/{total_cat} = {acc_cat:.2f}%")
        
        cost_time = int(time.time() - start_time)
        logger.info(f"Total inference time: {cost_time // 3600}h {(cost_time % 3600) // 60}m {cost_time % 60}s")

    dist.destroy_process_group()


if __name__ == "__main__":
    main()
