import os
import sys
import json
import argparse
import logging
import time
import traceback  
from datetime import datetime
from collections import defaultdict
import re

import pandas as pd
import torch
import torch.distributed as dist
from tqdm import tqdm
from decord import VideoReader
from transformers import AutoProcessor
from modeling_qwen2_vl import Qwen2VLForConditionalGeneration
from qwen_vl_utils import process_vision_info

PROMPT_TEMPLATE = """Select the best answer to the following multiple-choice question based on the video. Respond with only the letter (A, B, C, or D) of the correct option.
{question}
Options: {options}
The best answer is:"""

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
fmt_str = "%(asctime)s %(levelname)5s | %(message)s"
fmt = logging.Formatter(fmt_str)

def setup_logging(args, local_rank):
    """Configure logger, distinguishing between main process and worker processes"""
    curr_time = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_filename = f"{args.run_name}_{curr_time}_rank{local_rank}.log"
    log_path = os.path.join(args.result_dir, 'log', log_filename)

    file_handler = logging.FileHandler(log_path)
    file_handler.setFormatter(fmt)
    logger.addHandler(file_handler)

    if local_rank == 0:
        stream_handler = logging.StreamHandler(sys.stdout)
        stream_handler.setFormatter(fmt)
        logger.addHandler(stream_handler)
    return curr_time


def extract_answer(s: str) -> str:
    """Extract answer option letter (A, B, C, or D) from model response"""
    s = s.strip()
    match = re.search(r"\(([A-D])\)", s)
    if match:
        return match.group(1)
    answer_prefixes = [
        "The best answer is", "The correct answer is", "The answer is", "The answer",
        "The best option is", "The correct option is", "Best answer:", "Best option:",
    ]
    for prefix in answer_prefixes:
        if s.lower().startswith(prefix.lower()):
            s = s[len(prefix):].strip()
            break 

    matches = re.search(r"^[A-D]", s)
    if matches:
        return matches.group(0)

    matches = re.search(r"\b[A-D]\b", s)
    if matches:
        return matches.group(0)

    return ""


def merge_jsonl_files(base_path, world_size):
    """Merge multiple jsonl files generated by different rank processes into a single file"""
    merged_data = []
    for rank in range(world_size):
        file_path = f"{base_path}_rank{rank}.jsonl"
        if os.path.exists(file_path):
            with open(file_path, 'r', encoding='utf-8') as f:
                for line in f:
                    try:
                        merged_data.append(json.loads(line))
                    except json.JSONDecodeError:
                        logger.warning(f"Failed to parse line in file {file_path}: {line.strip()}")
                        continue
            os.remove(file_path) 

    if not merged_data:
        logger.warning(f"No {base_path}_rank*.jsonl files found to merge.")
        return

    merged_file_path = f"{base_path}_merged.jsonl"
    with open(merged_file_path, 'w', encoding='utf-8') as f:
        for item in merged_data:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
    logger.info(f"Successfully merged {len(merged_data)} records to {merged_file_path}")


def main():
    parser = argparse.ArgumentParser(description="Distributed evaluation on Video-MME dataset using Qwen2-VL")
    parser.add_argument("--model_path", type=str, required=True, help="Path to Qwen2-VL model weights (local path or Hugging Face ID)")
    parser.add_argument("--video_dir", type=str, required=True, help="Directory containing Video-MME video files")
    parser.add_argument("--task_parquet", type=str, required=True, help="Path to Video-MME task description parquet file")
    parser.add_argument("--result_dir", type=str, default="eval_results/videomme", help="Directory for storing results, logs, and outputs")
    parser.add_argument("--run_name", type=str, default="qwen2vl_videomme_eval", help="Name of this run, used for generating filenames")
    parser.add_argument("--n_frames", type=int, default=768, help="Target number of frames to sample per video (consider reducing default)") 
    parser.add_argument("--min_frames", type=int, default=8, help="Minimum number of frames for video processing") 
    parser.add_argument("--max_new_tokens", type=int, default=128, help="Maximum number of new tokens to generate")

    args = parser.parse_args()
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    torch.cuda.set_device(local_rank)
    dist.init_process_group(backend='nccl')
    world_size = dist.get_world_size()
    is_main_process = local_rank == 0
    if is_main_process:
        for subdir in ['output', 'log']:
            os.makedirs(os.path.join(args.result_dir, subdir), exist_ok=True)
    dist.barrier()

    curr_time = setup_logging(args, local_rank)
    output_jsonl_path = os.path.join(args.result_dir, 'output', f"{args.run_name}_{curr_time}_rank{local_rank}.jsonl")

    logger.info(f"--- [Rank {local_rank}/{world_size}] Process started ---")
    logger.info(f"Run configuration: {vars(args)}")

    # Model and Preprocessor Loading
    if not is_main_process: dist.barrier() 
    
    logger.info(f"[Rank {local_rank}] Starting to load model: {args.model_path}")
    model = Qwen2VLForConditionalGeneration.from_pretrained(
        args.model_path,
        torch_dtype="auto",
        device_map=f"cuda:{local_rank}",
        attn_implementation="sdpa", 
    )
    processor = AutoProcessor.from_pretrained(args.model_path)
    
    if is_main_process: dist.barrier() 

    try:
        task_df_full = pd.read_parquet(args.task_parquet)
    except Exception as e:
        logger.error(f"Failed to read Parquet file {args.task_parquet}. Error: {e}")
        dist.destroy_process_group()
        sys.exit(1)

    num_samples = len(task_df_full)
    indices = list(range(num_samples))
    rank_indices = indices[local_rank::world_size]
    task_df = task_df_full.iloc[rank_indices].copy()
    task_df = task_df[task_df['duration'] != 'short'].copy()
    logger.info(f"[Rank {local_rank}] Data splitting complete. Will process {len(task_df)} / {num_samples} samples.")

    processed_ids = set()
    if os.path.exists(output_jsonl_path):
        logger.info(f"[Rank {local_rank}] Resuming progress from existing output file: {output_jsonl_path}")
        with open(output_jsonl_path, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    processed_ids.add(json.loads(line)['question_id'])
                except (json.JSONDecodeError, KeyError):
                    continue
    if processed_ids:
        original_count = len(task_df)
        task_df = task_df[~task_df['question_id'].isin(processed_ids)]
        logger.info(f"[Rank {local_rank}] Skipped {len(processed_ids)} completed tasks. Remaining: {len(task_df)}/{original_count}.")

    start_time = time.time()
    results = []

    progress_bar = tqdm(task_df.itertuples(), total=len(task_df), disable=not is_main_process, desc=f"Rank {local_rank} Inference")
    for row in progress_bar:
        try:
            video_path = os.path.join(args.video_dir, row.videoID + '.mp4')
            if not os.path.exists(video_path):
                logger.warning(f"Video file not found: {video_path}, skipping sample {row.question_id}")
                continue

            try:
                vr = VideoReader(video_path) 
                video_frame_count = len(vr)
            except Exception as e:
                logger.error(
                    f"Failed to read video {video_path}, skipping.\n"
                    f"  Error type: {type(e).__name__}\n"
                    f"  Error message: {e}\n"
                    f"  Traceback: {traceback.format_exc()}"
                )
                continue

            final_nframes = max(args.min_frames, min(args.n_frames, video_frame_count))
            if final_nframes != args.n_frames:
                logger.info(f"ID {row.question_id}: Requested frame count {args.n_frames} exceeds video valid range [1, {video_frame_count}]. Adjusted to {final_nframes}.")                
            
            options_str = '\n'.join([f"{chr(65+i)}. {opt}" for i, opt in enumerate(row.options)])
            question_text = PROMPT_TEMPLATE.format(question=row.question, options=options_str)

            # Prepare messages list, using "file://" URI format, and pass nframes in the dict
            messages = [{
                "role": "user",
                "content": [
                    {
                        "type": "video",
                        "video": f"file://{os.path.abspath(video_path)}",
                        "nframes": final_nframes,
                    },
                    {"type": "text", "text": question_text},
                ]
            }]

            # Prepare pure text portion
            text = processor.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True
            )

            # Get correct patch_size from model config
            patch_size = model.config.vision_config.patch_size

            # Use official helper function with correct parameters to extract visual inputs
            image_inputs, video_inputs = process_vision_info(
                messages,
                image_patch_size=patch_size
            )

            inputs = processor(
                text=[text],
                images=image_inputs,
                videos=video_inputs,
                return_tensors="pt",
            ).to(model.device)
            generated_ids = model.generate(**inputs, max_new_tokens=args.max_new_tokens, do_sample=False)
            generated_ids_trimmed = generated_ids[:, inputs['input_ids'].shape[1]:]
            response = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

            output_dict = {
                'question_id': row.question_id,
                'video_id': row.videoID,
                'question': row.question,
                'options': row.options.tolist(),
                'answer': row.answer,
                'response': response,
                'extracted_answer': extract_answer(response)
            }
            
            with open(output_jsonl_path, 'a', encoding='utf-8') as f:
                f.write(json.dumps(output_dict, ensure_ascii=False) + '\n')
            results.append(output_dict)

        except Exception as e:
            logger.error(f"[Rank {local_rank}] Critical error processing {row.question_id}: {e}")
            traceback.print_exc() 

    end_time = time.time()
    cost_time = int(end_time - start_time)
    logger.info(f"[Rank {local_rank}] Inference completed. Time elapsed: {cost_time} seconds.")

    dist.barrier()
    if is_main_process:
        logger.info("--- All processes completed. Starting result aggregation ---")
        base_output_path = os.path.join(args.result_dir, 'output', f"{args.run_name}_{curr_time}")
        merge_jsonl_files(base_output_path, world_size)

        merged_file_path = f"{base_output_path}_merged.jsonl"
        if os.path.exists(merged_file_path):
            final_df = pd.read_json(merged_file_path, lines=True)
            total = len(final_df)
            correct = (final_df['extracted_answer'] == final_df['answer']).sum()
            if total > 0:
                accuracy = 100 * correct / total
                logger.info(f"[Overall Results]: Total={total}, Correct={correct}, Accuracy={accuracy:.2f}%")
            else:
                logger.info("No valid evaluation results.")
        else:
            logger.warning("Merged result file not found; cannot calculate final accuracy.")

    dist.destroy_process_group()


if __name__ == "__main__":
    main()
