#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/llava_onevision/modular_llava_onevision.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_llava_onevision.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2024 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Tuple
from typing import List
import math
from dataclasses import dataclass
from typing import Optional, Union, Tuple

import numpy as np
import torch
from torch import nn
import torch.nn.functional as F


from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.image_processing_utils import select_best_resolution
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_outputs import BaseModelOutputWithPast, ModelOutput
from transformers.modeling_utils import PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, can_return_tuple
from .qwen2 import Qwen2Model, apply_rotary_pos_emb, repeat_kv
from transformers import AutoModel
from .configuration_llava_onevision import LlavaOnevisionConfig


@dataclass
@auto_docstring(
    custom_intro="""
    Base class for Llava outputs, with hidden states and attentions.
    """
)
class LlavaOnevisionModelOutputWithPast(BaseModelOutputWithPast):
    r"""
    past_key_values (`Cache`, *optional*, returned when `use_cache=True` is passed or when `config.use_cache=True`):
        It is a [`~cache_utils.Cache`] instance. For more details, see our [kv cache guide](https://huggingface.co/docs/transformers/en/kv_cache).

        Contains pre-computed hidden-states (key and values in the self-attention blocks) that can be used (see
        `past_key_values` input) to speed up sequential decoding.
    image_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor` of size `(batch_size, num_images, sequence_length, hidden_size)`.
        image_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    video_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor`  of size `(batch_size * num_frames, num_videos, sequence_length, hidden_size)`.
        video_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    """

    image_hidden_states: Optional[torch.FloatTensor] = None

    video_hidden_states: Optional[torch.FloatTensor] = None


@dataclass
@auto_docstring(
    custom_intro="""
    Base class for LlavaOnevision causal language model (or autoregressive) outputs.
    """
)
class LlavaOnevisionCausalLMOutputWithPast(ModelOutput):
    r"""
    loss (`torch.FloatTensor` of shape `(1,)`, *optional*, returned when `labels` is provided):
        Language modeling loss (for next-token prediction).
    logits (`torch.FloatTensor` of shape `(batch_size, sequence_length, config.vocab_size)`):
        Prediction scores of the language modeling head (scores for each vocabulary token before SoftMax).
    past_key_values (`Cache`, *optional*, returned when `use_cache=True` is passed or when `config.use_cache=True`):
        It is a [`~cache_utils.Cache`] instance. For more details, see our [kv cache guide](https://huggingface.co/docs/transformers/en/kv_cache).

        Contains pre-computed hidden-states (key and values in the self-attention blocks) that can be used (see
        `past_key_values` input) to speed up sequential decoding.
    image_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor` of size (batch_size * num_patches, num_images, sequence_length, hidden_size)`.
        image_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    video_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor`  of size `(batch_size * num_frames, num_videos, sequence_length, hidden_size)`.
        video_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    """

    loss: Optional[torch.FloatTensor] = None
    logits: Optional[torch.FloatTensor] = None
    past_key_values: Optional[Cache] = None
    hidden_states: Optional[tuple[torch.FloatTensor]] = None
    attentions: Optional[tuple[torch.FloatTensor]] = None
    image_hidden_states: Optional[torch.FloatTensor] = None

    video_hidden_states: Optional[torch.FloatTensor] = None


@auto_docstring
class LlavaOnevisionPreTrainedModel(PreTrainedModel):
    config: LlavaOnevisionConfig
    base_model_prefix = ""
    supports_gradient_checkpointing = True
    _no_split_modules = ["LlamaDecoderLayer"]
    _skip_keys_device_placement = "past_key_values"

    _supports_flash_attn = True
    _supports_sdpa = True

    _can_compile_fullgraph = True
    _supports_flex_attn = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = getattr(self.config, "initializer_range",
                      self.config.get_text_config().initializer_range)

        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, LlavaOnevisionModel):
            embed_std = 1 / math.sqrt(self.config.text_config.hidden_size)
            module.image_newline.data.normal_(mean=0.0, std=embed_std)


class LlavaOnevisionMultiModalProjector(nn.Module):
    def __init__(self, config: LlavaOnevisionConfig):
        super().__init__()
        # We have hidden_size * the number of vision feature layers
        num_feature_layers = 1 if isinstance(
            config.vision_feature_layer, int) else len(config.vision_feature_layer)
        self.linear_1 = nn.Linear(
            config.vision_config.hidden_size * num_feature_layers,
            config.text_config.hidden_size,
            bias=config.multimodal_projector_bias,
        )
        self.act = ACT2FN[config.projector_hidden_act]
        self.linear_2 = nn.Linear(
            config.text_config.hidden_size, config.text_config.hidden_size, bias=config.multimodal_projector_bias
        )

    def forward(self, image_features):
        hidden_states = self.linear_1(image_features)
        hidden_states = self.act(hidden_states)
        hidden_states = self.linear_2(hidden_states)
        return hidden_states


def get_anyres_image_grid_shape(image_size, grid_pinpoints, patch_size):
    """
    Calculate the shape of the image patch grid after the preprocessing for images of any resolution.

    Args:
        image_size (`tuple`):
            The size of the input image in the format (width, height).
        grid_pinpoints (`List`):
            A list containing possible resolutions. Each item in the list should be a tuple or list
            of the form `(height, width)`.
        patch_size (`int`):
            The size of each image patch.

    Returns:
        tuple: The shape of the image patch grid in the format (width, height).
    """
    if not isinstance(grid_pinpoints, list):
        raise TypeError("grid_pinpoints should be a list of tuples or lists")

    # ! VERY IMPORTANT if image_size is tensor, must convert to into tuple, otherwise it will cause wrong calculate
    if not isinstance(image_size, (list, tuple)):
        if not isinstance(image_size, (torch.Tensor, np.ndarray)):
            raise TypeError(
                f"image_size invalid type: {type(image_size)} not valid, should be either list, tuple, np.ndarray or tensor"
            )
        image_size = image_size.tolist()

    height, width = select_best_resolution(image_size, grid_pinpoints)
    return height // patch_size, width // patch_size


def image_size_to_num_patches(image_size, grid_pinpoints, patch_size: int):
    """
    Calculate the number of patches after the preprocessing for images of any resolution.

    Args:
        image_size (`torch.LongTensor` or `np.ndarray` or `tuple[int, int]`):
            The size of the input image in the format (height, width). ?
        grid_pinpoints (`List`):
            A list containing possible resolutions. Each item in the list should be a tuple or list
            of the form `(height, width)`.
        patch_size (`int`):
            The size of each image patch.

    Returns:
        int: the number of patches
    """
    if not isinstance(grid_pinpoints, list):
        raise TypeError("grid_pinpoints should be a list of tuples or lists")

    # ! VERY IMPORTANT if image_size is tensor, must convert to into tuple, otherwise it will cause wrong calculate
    if not isinstance(image_size, (list, tuple)):
        if not isinstance(image_size, (torch.Tensor, np.ndarray)):
            raise TypeError(
                f"image_size invalid type {type(image_size)} with value {image_size}")
        image_size = image_size.tolist()

    best_resolution = select_best_resolution(image_size, grid_pinpoints)
    height, width = best_resolution
    num_patches = 0
    # consider change to ceil(height/patch_size)*ceil(width/patch_size) + 1
    for i in range(0, height, patch_size):
        for j in range(0, width, patch_size):
            num_patches += 1
    # add the base patch
    num_patches += 1
    return num_patches


def unpad_image(tensor, original_size):
    """
    Unpads a PyTorch tensor of a padded and resized image.

    Args:
        tensor (`torch.Tensor`):
            The image tensor, assumed to be of shape (num_channels, height, width).
        original_size (`tuple`):
            The original size of the image (height, width).

    Returns:
        `torch.Tensor`: The unpadded image tensor.
    """
    if not isinstance(original_size, (list, tuple)):
        if not isinstance(original_size, (torch.Tensor, np.ndarray)):
            raise TypeError(
                f"image_size invalid type: {type(original_size)} not valid, should be either list, tuple, np.ndarray or tensor"
            )
        original_size = original_size.tolist()
    original_height, original_width = original_size
    current_height, current_width = tensor.shape[1:]

    original_aspect_ratio = original_width / original_height
    current_aspect_ratio = current_width / current_height

    if original_aspect_ratio > current_aspect_ratio:
        scale_factor = current_width / original_width
        new_height = int(round(original_height * scale_factor, 7))
        padding = (current_height - new_height) // 2
        unpadded_tensor = tensor[:, padding: current_height - padding, :]
    else:
        scale_factor = current_height / original_height
        new_width = int(round(original_width * scale_factor, 7))
        padding = (current_width - new_width) // 2
        unpadded_tensor = tensor[:, :, padding: current_width - padding]

    return unpadded_tensor


@auto_docstring(
    custom_intro="""
    The Llava-Next model which consists of a vision backbone and a language model without language modeling head.
    """
)
class LlavaOnevisionModel(LlavaOnevisionPreTrainedModel):
    _checkpoint_conversion_mapping = {"language_model.model": "language_model"}

    def __init__(self, config):
        super().__init__(config)
        self.vision_tower = AutoModel.from_config(config.vision_config)

        self.multi_modal_projector = LlavaOnevisionMultiModalProjector(config)
        embed_std = 1 / math.sqrt(config.text_config.hidden_size)
        self.image_newline = nn.Parameter(torch.randn(
            config.text_config.hidden_size, dtype=self.dtype) * embed_std)

        self.vocab_size = config.text_config.vocab_size
        self.language_model = Qwen2Model(config.text_config)
        self.pad_token_id = self.config.pad_token_id if self.config.pad_token_id is not None else -1

        # new
        self.streaming_state = {
            "past_key_values": None,
            "fusion_counts": None,
            "last_frame_hidden_states": None,
            "logical_seq_len": 0,
            "logical_positions": 0,
        }
        self.inter_frame_threshold = 0.75
        self.intra_frame_threshold = 0.8  # intra frame threshold
        self.kv_cache_token_limit = 6000  # KV size per layer
        self.kv_cache_token_limit_per_layer = self.kv_cache_token_limit
        self.gsim_threshold = 0.5  # κ (kappa) for GSim gating
        self.gsim_temperature = 150  # τ (tau) for GSim softmax

        self.post_init()

    def reset_streaming_state(self):
        """
        reset the state of streaming
        """
        print("--- Resetting model streaming state for new sample ---")
        self.streaming_state = {
            "past_key_values": None,
            "fusion_counts": None,
            "last_frame_hidden_states": None,
            "logical_seq_len": 0,
        }



    @torch.no_grad()
    def _proxy_prefill_and_get_queries(self, past_key_values: Cache):
        """
        [Refactored Version] Generate proxy queries for importance scoring.
        This version uses safe API access to KV Cache and dynamically generates correct 
        Attention Masks and position encodings for each layer to precisely adapt to 
        complex scenarios where layer lengths vary.
        """
        device = self.get_input_embeddings().weight.device
        proxy_ids = torch.tensor([[151645, 151644, 77091, 198]], device=device)
        proxy_embeds = self.get_input_embeddings()(proxy_ids)
        bsz, q_len, _ = proxy_embeds.shape
        past_len = self.streaming_state["logical_seq_len"]
        proxy_pos_ids = torch.arange(
            past_len, past_len + q_len, device=device
        ).unsqueeze(0)
        fusion_counts_history = self.streaming_state["fusion_counts"]
        # 1. Create a temporary, safe pkv clone for simulating forward propagation
        pkv_clone = DynamicCache()
        if past_key_values is not None and past_key_values.get_seq_length(0) > 0:
            # Iterate through all layers to safely populate the clone
            for layer_idx in range(len(self.language_model.layers)):
                k, v = past_key_values[layer_idx]
                pkv_clone.update(k.clone(), v.clone(), layer_idx)

        proxy_queries_per_layer = []
        hidden_states = proxy_embeds

        # 2. Simulate forward propagation layer by layer
        for layer_idx, layer in enumerate(self.language_model.layers):
            layernorm_output = layer.input_layernorm(hidden_states)

            # 3. Dynamically compute position information (RoPE) for current layer
            #    This is critical: each layer has its own independent past_len
            current_past_len = pkv_clone.get_seq_length(layer_idx)

            # Your RoPE computation logic (assuming rotary_emb and apply_rotary_pos_emb are correct)
            cos, sin = self.language_model.rotary_emb(
                proxy_embeds, proxy_pos_ids)
            position_embeddings = (cos, sin)

            # 4. Extract rotation-applied query vectors (q_rot) for scoring
            q_vectors = layer.self_attn.q_proj(layernorm_output)
            q_vectors = q_vectors.view(
                bsz, q_len, layer.self_attn.config.num_attention_heads, layer.self_attn.head_dim
            ).transpose(1, 2)
            q_rot, _ = apply_rotary_pos_emb(q_vectors, q_vectors, cos, sin)
            proxy_queries_per_layer.append(q_rot)

            total_kv_len = current_past_len + q_len

            attention_mask = torch.zeros(
                (bsz, 1, q_len, total_kv_len), dtype=hidden_states.dtype, device=device
            )
            if q_len > 1:
                causal_mask_bool = torch.triu(
                    torch.ones((q_len, q_len), device=device, dtype=torch.bool), diagonal=1
                )
                attention_mask[..., :, current_past_len:].masked_fill_(
                    causal_mask_bool, torch.finfo(hidden_states.dtype).min
                )

            # [Added] Add fusion_counts bias
            if layer_idx < len(fusion_counts_history):
                fc_layer = fusion_counts_history[layer_idx]
                if fc_layer is not None and fc_layer.numel() > 0:
                    if fc_layer.dim() == 1:
                        fc_layer = fc_layer.unsqueeze(0)
                    attention_bias = torch.log1p(
                        fc_layer - 1).to(attention_mask.dtype)
                    attention_bias = attention_bias.unsqueeze(1).unsqueeze(1)

                    bias_len = min(current_past_len, attention_bias.shape[-1])
                    if bias_len > 0:
                        attention_mask[..., :,
                                       :bias_len] += attention_bias[..., :bias_len]
            cache_pos = torch.arange(
                current_past_len, current_past_len + q_len, device=device).unsqueeze(0)  
            # 6. Simulate complete attention computation to update hidden_states for next layer
            #    Note: pkv_clone will be internally updated during this call
            attn_output, _ = layer.self_attn(
                hidden_states=layernorm_output,
                position_embeddings=position_embeddings,
                attention_mask=attention_mask,
                past_key_values=pkv_clone,
                use_cache=True,
                cache_position=cache_pos  
            )

            # Simulate residual connection and MLP
            hidden_states = hidden_states + attn_output
            hidden_states = hidden_states + \
                layer.mlp(layer.post_attention_layernorm(hidden_states))

        return proxy_queries_per_layer

    def _bipartite_merge_and_replace_single(
        self,
        frame_hs: torch.Tensor,
        in_frame_threshold: float
    ) -> Tuple[torch.Tensor, torch.LongTensor]:
        """
        Single bipartite graph merge: replace target position with merged vector 
        and return indices of merged-away tokens.
        This function precisely controls gradients: decision process has no gradient, 
        merge process has gradient.
        """
        if frame_hs.shape[0] < 2:
            return frame_hs, torch.tensor([], dtype=torch.long, device=frame_hs.device)

        frame_hs_detached = frame_hs.detach()
        metric_norm = frame_hs_detached / \
            frame_hs_detached.norm(dim=-1, keepdim=True)
        metric_norm = metric_norm.unsqueeze(0)
        a, b = metric_norm[:, ::2, :], metric_norm[:, 1::2, :]

        if a.shape[1] == 0 or b.shape[1] == 0:
            return frame_hs, torch.tensor([], dtype=torch.long, device=frame_hs.device)

        scores = a @ b.transpose(-1, -2)
        node_max, node_idx = scores.max(dim=-1)
        edge_idx = (node_max > in_frame_threshold).squeeze(0)

        if not edge_idx.any():
            return frame_hs, torch.tensor([], dtype=torch.long, device=frame_hs.device)

        a_indices_relative = torch.arange(a.shape[1], device=frame_hs.device)
        a_dropped_indices_relative = a_indices_relative[edge_idx]
        dropped_indices_relative = a_dropped_indices_relative * 2

        updated_frame_hs = frame_hs.clone()
        a_orig, b_orig = frame_hs[::2, :], frame_hs[1::2, :]
        merged_sum = torch.zeros_like(b_orig, dtype=frame_hs.dtype)
        counts = torch.zeros(
            b_orig.shape[0], dtype=torch.int64, device=frame_hs.device)
        b_dest_map = node_idx.squeeze(0)[edge_idx]
        merged_sum.index_add_(0, b_dest_map, a_orig[edge_idx])
        counts.index_add_(0, b_dest_map, torch.ones_like(
            b_dest_map, dtype=torch.int64))
        b_consumed_indices_relative = torch.unique(b_dest_map)
        merged_sum.index_add_(0, b_consumed_indices_relative,
                              b_orig[b_consumed_indices_relative])
        counts.index_add_(0, b_consumed_indices_relative, torch.ones_like(
            b_consumed_indices_relative, dtype=torch.int64))
        final_merged_vectors = merged_sum[b_consumed_indices_relative] / \
            counts[b_consumed_indices_relative].unsqueeze(
                -1).to(frame_hs.dtype)

        original_b_consumed_indices = b_consumed_indices_relative * 2 + 1
        updated_frame_hs[original_b_consumed_indices] = final_merged_vectors

        return updated_frame_hs, dropped_indices_relative


    def _compress_kv_cache(self):
        """
        KV Cache compression using a "uniform + fixed-ratio + dynamic entropy" three-in-one hybrid strategy.
        """
        pkv = self.streaming_state["past_key_values"]
        if pkv is None or pkv.get_seq_length(layer_idx=0) == 0:
            return

        # 1. Initialization and configuration 
        try:
            kv_dtype = pkv.key_cache[0].dtype if hasattr(
                pkv, 'key_cache') and pkv.key_cache else torch.bfloat16
        except (IndexError, AttributeError):
            kv_dtype = torch.bfloat16
        try:
            device = pkv.key_cache[0].device if hasattr(
                pkv, 'key_cache') and pkv.key_cache else self.visual.get_device()
        except (IndexError, AttributeError):
            device = self.visual.get_device() if hasattr(self, 'visual') else torch.device(
                'cuda' if torch.cuda.is_available() else 'cpu')

        num_layers = len(self.language_model.layers)
        fusion_counts = self.streaming_state["fusion_counts"]
        total_budget = self.kv_cache_token_limit_per_layer * num_layers
        current_total_len = sum(pkv.get_seq_length(layer_idx=i)
                                for i in range(num_layers))

        if current_total_len <= total_budget:
            return

        # 2. Compute importance scores and entropy (restore entropy computation)
        pkv_clone = DynamicCache()
        if pkv.get_seq_length() > 0:
            for layer_idx in range(num_layers):
                k, v = pkv[layer_idx]
                pkv_clone.update(k.clone(), v.clone(), layer_idx)

        proxy_queries = self._proxy_prefill_and_get_queries(pkv_clone)
        num_kv_groups = self.language_model.layers[0].self_attn.num_key_value_groups

        layer_scores = []
        layer_entropies = []  

        for layer_idx in range(num_layers):
            k_layer, v_layer = pkv[layer_idx]
            q_proxy = proxy_queries[layer_idx]

            with torch.autocast(device_type=k_layer.device.type, dtype=kv_dtype):
                k_layer_repeated = repeat_kv(k_layer, num_kv_groups)
                attn_scores = torch.matmul(
                    q_proxy, k_layer_repeated.transpose(-2, -1))
                scores = attn_scores.mean(dim=2).mean(dim=1).squeeze(0)

                fc_layer = fusion_counts[layer_idx]
                if fc_layer.numel() == scores.numel():
                    attention_bias = torch.log1p(
                        fc_layer.squeeze(0) - 1).to(scores.device, scores.dtype)
                    scores = scores+torch.sqrt_(attention_bias+1)

                v_norm = v_layer.norm(p=2, dim=-1).mean(dim=1).squeeze(0)
                log_v_norm = torch.log(
                    v_norm + 1e-9).to(scores.device, scores.dtype)
                scores = scores

            layer_scores.append(scores)

            if scores.numel() > 0:
                probs = F.softmax(scores.to(torch.float32), dim=0)
                entropy = -torch.sum(probs * torch.log(probs + 1e-9))
            else:
                entropy = torch.tensor(0.0, device=scores.device)
            layer_entropies.append(torch.log1p_(entropy) * log_v_norm.mean())

        new_keys = [None] * num_layers
        new_values = [None] * num_layers
        new_fusion_counts = [None] * num_layers
        layer_lens = [pkv.get_seq_length(i) for i in range(num_layers)]

        if total_budget > 0:
            weight_uniform = 0.4
            weight_static = 0.575
            weight_entropy = 1-weight_uniform-weight_static
            uniform_proportions = torch.full(
                (num_layers,), 1.0 / num_layers, device=device)
            static_ratios_list = [42, 40, 39, 39, 39, 39, 39, 40, 43, 45, 47,
                                  50, 50, 50, 50, 49, 46, 43, 40, 37, 33, 28, 25, 21, 18, 14, 11, 7]
            if len(static_ratios_list) != num_layers:
                raise ValueError(
                    f"Provided static ratio count ({len(static_ratios_list)}) does not match model layer count ({num_layers}).")
            static_ratios_tensor = torch.tensor(
                static_ratios_list, dtype=torch.float32, device=device)
            static_proportions = static_ratios_tensor / static_ratios_tensor.sum()

            # 3. Dynamic entropy-based ratio
            entropies_tensor = torch.stack(layer_entropies)
            # Normalize entropy values to be scale-invariant
            entropies_tensor = entropies_tensor - entropies_tensor.min()
            total_entropy = entropies_tensor.sum()

            if total_entropy <= 1e-9:  
                entropy_proportions = uniform_proportions.clone()
            else:
                entropy_proportions = entropies_tensor / total_entropy

            # 4. Weighted mixing to get final proportions
            proportions_to_use = (weight_uniform * uniform_proportions +
                                  weight_static * static_proportions +
                                  weight_entropy * entropy_proportions)

            layer_lens_tensor = torch.tensor(layer_lens, device=device)
            num_to_keep = proportions_to_use * total_budget
            over_allocated_mask = num_to_keep > layer_lens_tensor.float()
            excess_budget = (num_to_keep[over_allocated_mask] -
                             layer_lens_tensor[over_allocated_mask].float()).sum()
            num_to_keep = torch.min(num_to_keep, layer_lens_tensor.float())

            if excess_budget > 0:
                under_allocated_mask = ~over_allocated_mask
                if under_allocated_mask.any():
                    proportions_under = proportions_to_use[under_allocated_mask]
                    if proportions_under.sum() > 0:
                        proportions_under /= proportions_under.sum()
                        redistribution = proportions_under * excess_budget
                        current_under_values = num_to_keep[under_allocated_mask]
                        capacity_under = layer_lens_tensor[under_allocated_mask]
                        final_additions = torch.min(
                            redistribution, (capacity_under - current_under_values).float())
                        num_to_keep[under_allocated_mask] += final_additions

            floored_keeps = num_to_keep.floor().long()
            remainder = int(total_budget - floored_keeps.sum())
            if remainder > 0:
                fractional_parts = num_to_keep - floored_keeps.float()
                fractional_parts[floored_keeps >= layer_lens_tensor] = -1
                top_k_indices = torch.topk(fractional_parts, min(
                    remainder, (fractional_parts > 0).sum().item())).indices
                floored_keeps.scatter_add_(
                    0, top_k_indices, torch.ones_like(top_k_indices, dtype=torch.long))

            budgets_for_all_layers = floored_keeps.tolist()
        else:
            budgets_for_all_layers = [0] * num_layers

        print(
            f"KV Cache compression budgets per layer: {budgets_for_all_layers}")
        print(f"Verification sum: {sum(budgets_for_all_layers)}")

        new_keys = [None] * num_layers
        new_values = [None] * num_layers
        new_fusion_counts = [None] * num_layers

        for layer_idx in range(num_layers):
            budget_for_this_layer = int(budgets_for_all_layers[layer_idx])
            k_layer, v_layer = pkv[layer_idx]
            fc_layer = fusion_counts[layer_idx]
            current_len = k_layer.shape[2]

            if current_len <= budget_for_this_layer:
                new_keys[layer_idx] = k_layer
                new_values[layer_idx] = v_layer
                new_fusion_counts[layer_idx] = fc_layer
                continue

            if budget_for_this_layer == 0:
                new_keys[layer_idx] = torch.empty_like(k_layer[..., :0, :])
                new_values[layer_idx] = torch.empty_like(v_layer[..., :0, :])
                new_fusion_counts[layer_idx] = fc_layer[..., :0]
                continue

            scores_this_layer = layer_scores[layer_idx]
            _, elite_indices = torch.topk(
                scores_this_layer, k=budget_for_this_layer)
            final_indices = torch.sort(elite_indices).values

            new_keys[layer_idx] = k_layer.index_select(2, final_indices)
            new_values[layer_idx] = v_layer.index_select(2, final_indices)
            new_fusion_counts[layer_idx] = fc_layer.index_select(
                1, final_indices)

        new_cache = DynamicCache()

        # 2. Iterate through our filtered keys and values
        for i in range(num_layers):
            if new_keys[i] is not None and new_keys[i].shape[2] > 0:
                new_cache.update(new_keys[i], new_values[i], layer_idx=i)

        # Use official update() method to safely populate new cache
        self.streaming_state["past_key_values"] = new_cache

        # Update fusion_counts 
        self.streaming_state["fusion_counts"] = new_fusion_counts


    @torch.no_grad()
    def _insert_frame_prototypes(self, new_tokens_len: int):
        """
        After model forward propagation, compute and insert frame-level prototypes 
        into KV Cache for newly processed visual frames.
        This operation is performed independently for each layer.
        """
        pkv = self.streaming_state.get("past_key_values")
        if pkv is None or new_tokens_len == 0:
            return

        num_layers = len(self.language_model.layers)

        # 1. Get the starting position of newly added new_tokens in cache
        # Note: Here we assume layer lengths are consistent before operation, 
        # which holds true for our streaming model
        past_kv_len = pkv.get_seq_length(layer_idx=0) - new_tokens_len

        # 2. Compute importance scores for new tokens (similar to _compress_kv_cache logic)
        # We need a method to score only the new tokens.
        # Here we reuse the full scoring mechanism, then slice out the portion we care about.
        proxy_queries = self._proxy_prefill_and_get_queries(pkv)

        new_keys_per_layer = []
        new_values_per_layer = []
        new_fusion_counts_per_layer = []

        for layer_idx in range(num_layers):
            k_layer, v_layer = pkv[layer_idx]
            new_k = k_layer[:, :, past_kv_len:, :]
            new_v = v_layer[:, :, past_kv_len:, :]

            if new_k.shape[2] == 0:  
                new_keys_per_layer.append(k_layer)
                new_values_per_layer.append(v_layer)
                new_fusion_counts_per_layer.append(
                    self.streaming_state["fusion_counts"][layer_idx])
                continue

            # Extract K, V just generated by the new frame
            q_proxy = proxy_queries[layer_idx]
            num_kv_groups = self.language_model.layers[layer_idx].self_attn.num_key_value_groups
            k_layer_repeated = repeat_kv(new_k, num_kv_groups)
            attn_scores = torch.matmul(
                q_proxy, k_layer_repeated.transpose(-2, -1))

            # Compute attention scores with new K using proxy queries
            importance_scores = attn_scores.mean(dim=2).mean(dim=1).squeeze(0)

            # Aggregate scores into importance per token
            normalized_scores = F.softmax(importance_scores.to(
                torch.float32), dim=0).to(new_k.dtype)

            # 3. Compute frame prototype (Equation 2)
            # Normalize importance scores -> alpha_j
            k_prototype = torch.sum(
                new_k * normalized_scores.view(1, 1, -1, 1), dim=2, keepdim=True)
            v_prototype = torch.sum(
                new_v * normalized_scores.view(1, 1, -1, 1), dim=2, keepdim=True)

            # 4. Insert prototype at the end of full K, V Cache
            final_k = torch.cat([k_layer, k_prototype], dim=2)
            final_v = torch.cat([v_layer, v_prototype], dim=2)

            new_keys_per_layer.append(final_k)
            new_values_per_layer.append(final_v)

            # 5. Update fusion_counts
            prototype_fusion_count = torch.tensor(
                [[1.0]], device=self.device)  # 原型Token的计数为1
            updated_fc = torch.cat(
                [self.streaming_state["fusion_counts"][layer_idx], prototype_fusion_count], dim=1)
            new_fusion_counts_per_layer.append(updated_fc)

        # 6. Safely update entire KV Cache state
        new_cache = DynamicCache()
        for i in range(num_layers):
            if new_keys_per_layer[i] is not None and new_keys_per_layer[i].shape[2] > 0:
                new_cache.update(
                    new_keys_per_layer[i], new_values_per_layer[i], layer_idx=i)

        self.streaming_state["past_key_values"] = new_cache
        self.streaming_state["fusion_counts"] = new_fusion_counts_per_layer

    def _bipartite_merge_and_replace(
        self,
        frame_hs: torch.Tensor,
        in_frame_threshold: float,
        max_iterations: int = 10
    ) -> Tuple[torch.Tensor, torch.LongTensor]:
        """
        Recursively performs token merging as described in https://arxiv.org/pdf/2210.09461.
        """
        if frame_hs.shape[0] < 2:
            return frame_hs, torch.tensor([], dtype=torch.long, device=frame_hs.device)

        current_frame_hs = frame_hs
        all_dropped_indices = []
        original_to_current_mapping = torch.arange(
            frame_hs.shape[0], device=frame_hs.device)

        for iteration in range(max_iterations):
            if current_frame_hs.shape[0] < 2:
                break

            updated_frame_hs, dropped_indices_current = self._bipartite_merge_and_replace_single(
                current_frame_hs, in_frame_threshold
            )

            if dropped_indices_current.numel() == 0:
                break

            dropped_indices_original = original_to_current_mapping[dropped_indices_current]
            all_dropped_indices.append(dropped_indices_original)

            keep_mask = torch.ones(
                current_frame_hs.shape[0], dtype=torch.bool, device=frame_hs.device)
            keep_mask[dropped_indices_current] = False
            original_to_current_mapping = original_to_current_mapping[keep_mask]
            current_frame_hs = updated_frame_hs[keep_mask]

        if all_dropped_indices:
            final_dropped_indices = torch.cat(all_dropped_indices, dim=0)
        else:
            final_dropped_indices = torch.tensor(
                [], dtype=torch.long, device=frame_hs.device)

        final_frame_hs = frame_hs.clone()
        final_keep_mask = torch.ones(
            frame_hs.shape[0], dtype=torch.bool, device=frame_hs.device)
        if final_dropped_indices.numel() > 0:
            final_keep_mask[final_dropped_indices] = False
        final_frame_hs[original_to_current_mapping] = current_frame_hs

        return final_frame_hs, final_dropped_indices

    def _create_streaming_attention_mask(
        self,
        q_len: int,
        past_key_values_length: int,
        combined_fusion_counts: Optional[torch.Tensor],
        device: torch.device,
        dtype: torch.dtype,
        batch_size: int = 1,  
    ) -> Optional[torch.Tensor]:
        """
        Create a correct attention mask (attn_bias) for streaming Prefill.
        """
        if q_len == 0:
            return None

        current_total_kv_len = past_key_values_length + q_len
        attn_bias = torch.zeros(
            batch_size, 1, q_len, current_total_kv_len, device=device, dtype=dtype)

        if q_len > 1:
            causal_mask = torch.triu(
                torch.ones(q_len, q_len, dtype=torch.bool, device=device),
                diagonal=1
            )
            attn_bias[..., :, past_key_values_length:].masked_fill_(
                causal_mask, torch.finfo(dtype).min
            )

        if combined_fusion_counts is not None:
            if combined_fusion_counts.dim() == 1:
                fc = combined_fusion_counts.unsqueeze(0).unsqueeze(
                    0).unsqueeze(0).expand(batch_size, -1, -1, -1)
            elif combined_fusion_counts.dim() == 2:
                fc = combined_fusion_counts.unsqueeze(1).unsqueeze(1)
            else:
                fc = combined_fusion_counts

            correction_len = min(current_total_kv_len, fc.shape[-1])
            if correction_len > 0:
                fc = fc.to(device=device, dtype=dtype)
                attention_correction = torch.log(
                    torch.clamp(fc[..., :correction_len], min=1.0)
                )
                attn_bias[..., :, :correction_len] += attention_correction
        return attn_bias

    def get_input_embeddings(self):
        return self.language_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.language_model.set_input_embeddings(value)

    def set_decoder(self, decoder):
        self.language_model = decoder

    def get_decoder(self):
        return self.language_model

    def pack_image_features(self, image_features, image_sizes, image_newline=None, vision_aspect_ratio="anyres_max_9"):
        """
        Reshape, unpad and then pack each image_feature into a single image_features tensor containing all visual vectors.
        """
        new_image_features = []
        feature_lens = []
        for image_idx, image_feature in enumerate(image_features):
            if image_feature.shape[0] > 1:
                base_image_feature = image_feature[0]
                image_feature = image_feature[1:]
                height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
                if height * width != base_image_feature.shape[0]:
                    raise ValueError(
                        "The number of patches is not consistent with the image size.")
                num_patch_height, num_patch_width = get_anyres_image_grid_shape(
                    image_sizes[image_idx],
                    self.config.image_grid_pinpoints,
                    self.config.vision_config.image_size,
                )
                image_feature = image_feature.view(
                    num_patch_height, num_patch_width, height, width, -1)
                image_feature = image_feature.permute(
                    4, 0, 2, 1, 3).contiguous()
                image_feature = image_feature.flatten(1, 2).flatten(2, 3)
                image_feature = unpad_image(
                    image_feature, image_sizes[image_idx])
                max_num_patches = int(vision_aspect_ratio.strip("anyres_max_"))
                channels, curr_height, curr_width = image_feature.shape
                ratio = math.sqrt(curr_height * curr_width /
                                  (max_num_patches * height**2))
                if ratio > 1.1:
                    image_feature = image_feature[None]
                    image_feature = nn.functional.interpolate(
                        image_feature, [int(curr_height // ratio), int(curr_width // ratio)], mode="bilinear"
                    )[0]
                if image_newline is not None:
                    image_feature = torch.cat(
                        (
                            image_feature,
                            image_newline[:, None, None]
                            .expand(*image_feature.shape[:-1], 1)
                            .to(image_feature.device, image_feature.dtype),
                        ),
                        dim=-1,
                    )
                image_feature = image_feature.flatten(1, 2).transpose(0, 1)
                image_feature = torch.cat(
                    (base_image_feature, image_feature), dim=0)
            else:
                image_feature = image_feature[0]
                if image_newline is not None:
                    image_feature = torch.cat(
                        (image_feature, image_newline[None].to(image_feature)), dim=0)
            new_image_features.append(image_feature)
            feature_lens.append(image_feature.size(0))
        feature_lens = torch.tensor(
            feature_lens, dtype=torch.long, device=image_features[0].device)
        return new_image_features, feature_lens

    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        image_sizes: torch.Tensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
    ):
        """
        Obtains image last hidden states from the vision tower and apply multimodal projection.
        """
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        if batch_num_images is None:
            need_patching = [True] * len(image_sizes)
        else:
            need_patching = [
                n == 1 for n in batch_num_images for _ in range(n)]
        image_num_patches = [
            image_size_to_num_patches(
                image_size=imsize,
                grid_pinpoints=self.config.image_grid_pinpoints,
                patch_size=self.config.vision_config.image_size,
            )
            if should_patch
            else 1
            for imsize, should_patch in zip(image_sizes, need_patching)
        ]
        if pixel_values.dim() == 5:
            _pixel_values_list = [pix_val[:num_patch] for pix_val, num_patch in zip(
                pixel_values, image_num_patches)]
            pixel_values = torch.cat(_pixel_values_list, dim=0)
        elif pixel_values.dim() != 4:
            raise ValueError(
                f"pixel_values of shape {pixel_values.shape}, expect to be of 4 or 5 dimensions")

        image_features = self.vision_tower(
            pixel_values, output_hidden_states=True)

        if isinstance(vision_feature_layer, int):
            selected_image_feature = image_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [image_features.hidden_states[layer_idx]
                       for layer_idx in vision_feature_layer]
            selected_image_feature = torch.cat(hs_pool, dim=-1)

        if vision_feature_select_strategy == "default":
            selected_image_feature = selected_image_feature[:, 1:]
        image_features = self.multi_modal_projector(selected_image_feature)
        image_features = torch.split(image_features, image_num_patches, dim=0)

        image_features, feature_lens = self.pack_image_features(
            image_features,
            image_sizes,
            image_newline=self.image_newline,
            vision_aspect_ratio=vision_aspect_ratio,
        )
        return image_features

    def get_placeholder_mask(
        self,
        input_ids: torch.LongTensor,
        inputs_embeds: torch.FloatTensor,
        image_features: Optional[torch.FloatTensor] = None,
        video_features: Optional[torch.FloatTensor] = None,
    ):
        """
        Obtains multimodal placeholder mask from `input_ids` or `inputs_embeds`.
        """
        if input_ids is None:
            special_image_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.image_token_id,
                             dtype=torch.long, device=inputs_embeds.device)
            )
            special_image_mask = special_image_mask.all(-1)
            special_video_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.video_token_id,
                             dtype=torch.long, device=inputs_embeds.device)
            )
            special_video_mask = special_video_mask.all(-1)
        else:
            special_image_mask = input_ids == self.config.image_token_id
            special_video_mask = input_ids == self.config.video_token_id

        n_image_tokens = special_image_mask.sum()
        special_image_mask = special_image_mask.unsqueeze(
            -1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if image_features is not None and inputs_embeds[special_image_mask].numel() != image_features.numel():
            raise ValueError(
                f"Image features and image tokens do not match: tokens: {n_image_tokens}, features {image_features.shape[0]}"
            )

        n_video_tokens = special_video_mask.sum()
        special_video_mask = special_video_mask.unsqueeze(
            -1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if video_features is not None and inputs_embeds[special_video_mask].numel() != video_features.numel():
            raise ValueError(
                f"Videos features and image tokens do not match: tokens: {n_video_tokens}, features {video_features.shape[0]}"
            )

        return special_image_mask, special_video_mask


    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.FloatTensor] = None,
        image_sizes: Optional[torch.LongTensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_sizes_videos: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> Union[tuple, LlavaOnevisionModelOutputWithPast]:
        print(f"self.inter_frame_threshold: {self.inter_frame_threshold}")
        print(f"self.intra_frame_threshold: {self.intra_frame_threshold}")
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        # --- Path 1: Standard Non-Streaming Inference ---
        # This path is used for tasks like single-image Q&A or when `use_cache=False`.
        # The logic remains standard as positions are not ambiguous.
        if not use_cache:
            if (input_ids is None) ^ (inputs_embeds is not None):
                raise ValueError(
                    "You must specify exactly one of input_ids or inputs_embeds")
            if inputs_embeds is None:
                inputs_embeds = self.get_input_embeddings()(input_ids)

            image_features, video_features = None, None
            if pixel_values is not None:
                image_features_list = self.get_image_features(
                    pixel_values, image_sizes, **kwargs)
                image_features = torch.cat(image_features_list, dim=0).to(
                    inputs_embeds.device, inputs_embeds.dtype)
                img_mask_3d, _ = self.get_placeholder_mask(
                    input_ids, inputs_embeds=inputs_embeds, image_features=image_features)
                inputs_embeds = inputs_embeds.masked_scatter(
                    img_mask_3d, image_features)

            if pixel_values_videos is not None:
                # This part is complex and might need further adaptation for non-streaming video
                video_features = self.get_video_features(
                    pixel_values_videos, **kwargs)
                newline = self.image_newline[None, None, :].repeat(
                    video_features.shape[0], 1, 1).to(video_features.device)
                video_features = torch.cat((video_features, newline), dim=1).flatten(
                    0, 1).to(inputs_embeds.device, inputs_embeds.dtype)
                _, vid_mask_3d = self.get_placeholder_mask(
                    input_ids, inputs_embeds=inputs_embeds, video_features=video_features)
                inputs_embeds = inputs_embeds.masked_scatter(
                    vid_mask_3d, video_features)

            # In non-streaming, position_ids are typically handled by the underlying model's default logic
            outputs = self.language_model(
                inputs_embeds=inputs_embeds,
                attention_mask=attention_mask,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=False,
                **kwargs
            )
            return LlavaOnevisionModelOutputWithPast(
                last_hidden_state=outputs.last_hidden_state,
                past_key_values=outputs.past_key_values,
                hidden_states=outputs.hidden_states,
                attentions=outputs.attentions,
                image_hidden_states=image_features,
                video_hidden_states=video_features
            )

        # --- Path 2: Streaming Inference (use_cache=True) ---
        if past_key_values is None or past_key_values.get_seq_length() == 0:
            self.reset_streaming_state()

        pkv = self.streaming_state.get("past_key_values") or DynamicCache()
        self.streaming_state["past_key_values"] = pkv

        num_layers = len(self.language_model.layers)
        if self.streaming_state.get("fusion_counts") is None:
            self.streaming_state["fusion_counts"] = [torch.empty(
                1, 0, device=self.device) for _ in range(num_layers)]

        if inputs_embeds is None:
            inputs_embeds = self.get_input_embeddings()(input_ids)

        # Process incoming data (video frame or text) and get compressed embeddings + fusion counts
        if pixel_values_videos is not None:
            # Video Frame processing logic with GSim... (assumed correct)
            # This logic outputs `current_embeds` and `current_fusion_counts`
            raw_features = self.get_video_features(
                pixel_values_videos, **kwargs)
            newline = self.image_newline[None, None, :].to(raw_features.device)
            original_frame_hs = torch.cat(
                (raw_features, newline), dim=1).squeeze(0)

            last_hs = self.streaming_state.get("last_frame_hidden_states")
            inter_keep_mask = torch.ones(
                original_frame_hs.shape[0], dtype=torch.bool, device=self.device)
            if last_hs is not None and last_hs.shape == original_frame_hs.shape:
                sim = F.cosine_similarity(
                    last_hs.detach(), original_frame_hs.detach(), dim=-1)
                inter_keep_mask = sim <= self.inter_frame_threshold
            self.streaming_state["last_frame_hidden_states"] = original_frame_hs.clone(
            )

            original_frame_hs = original_frame_hs[inter_keep_mask]

            if original_frame_hs.shape[0] < 2:
                final_processed_features = original_frame_hs
                s_factors = torch.ones(
                    final_processed_features.shape[0], device=self.device)
            else:
                _, dropped_indices_relative = self._bipartite_merge_and_replace(
                    original_frame_hs, self.intra_frame_threshold)
                if dropped_indices_relative.numel() == 0:
                    final_processed_features = original_frame_hs
                    s_factors = torch.ones(
                        final_processed_features.shape[0], device=self.device)
                else:
                    survivor_mask = torch.ones(
                        original_frame_hs.shape[0], dtype=torch.bool, device=self.device)
                    survivor_mask[dropped_indices_relative] = False
                    survivor_tokens = original_frame_hs[survivor_mask]

                    survivor_norm = F.normalize(survivor_tokens, p=2, dim=-1)
                    original_norm = F.normalize(original_frame_hs, p=2, dim=-1)
                    cosine_sim = torch.matmul(survivor_norm, original_norm.t())
                    gsim_matrix = torch.where(
                        cosine_sim >= self.gsim_threshold, cosine_sim, torch.tensor(0.0, device=self.device))
                    m_matrix = F.softmax(
                        gsim_matrix * self.gsim_temperature, dim=0)
                    s_factors = torch.sum(m_matrix, dim=1)
                    row_sums = torch.sum(m_matrix, dim=1, keepdim=True)
                    w_matrix = m_matrix / (row_sums + 1e-8)
                    final_processed_features = torch.matmul(
                        w_matrix, original_frame_hs)

            video_token_mask = (input_ids == self.config.video_token_id)
            text_embeds = inputs_embeds[~video_token_mask].view(
                1, -1, inputs_embeds.shape[-1])
            current_embeds = torch.cat(
                [text_embeds, final_processed_features.unsqueeze(0)], dim=1)

            text_counts = torch.ones(
                1, text_embeds.shape[1], device=self.device)
            vis_counts = s_factors.unsqueeze(0)
            current_fusion_counts = torch.cat([text_counts, vis_counts], dim=1)

        else:  # Pure text chunk
            current_embeds = inputs_embeds
            current_fusion_counts = torch.ones(
                1, current_embeds.shape[1], device=self.device)

        if current_embeds.shape[1] == 0:  # If all tokens were dropped
            return LlavaOnevisionModelOutputWithPast(last_hidden_state=torch.empty(1, 0, self.config.text_config.hidden_size, device=self.device, dtype=self.dtype), past_key_values=pkv)

        # Compress KV Cache before processing the new chunk
        if pixel_values_videos is not None:
            self._compress_kv_cache()

        # ==================== CORE LOGIC FOR POSITIONAL ENCODING ====================
        # 1. Get the current LOGICAL sequence length from our state manager.
        past_logical_len = self.streaming_state['logical_seq_len']

        # 2. Get the length of the NEW (and possibly compressed) input chunk.
        new_chunk_len = current_embeds.shape[1]

        # 3. Calculate the correct LOGICAL position_ids for this chunk.
        #    This ensures that even if the KV cache is compressed, the new tokens get
        #    positions as if they were appended to the full, uncompressed sequence.
        position_ids = torch.arange(
            past_logical_len, past_logical_len + new_chunk_len, device=self.device
        ).unsqueeze(0)

        # 4. CRITICAL: Update the logical sequence length for the *next* iteration.
        self.streaming_state['logical_seq_len'] += new_chunk_len
        # self.streaming_state['logical_seq_len'] += input_ids[0].shape[0]
        # ==========================================================================

        # Update fusion counts for each layer
        new_fc_history = [torch.cat([fc, current_fusion_counts], dim=1)
                          for fc in self.streaming_state["fusion_counts"]]
        self.streaming_state["fusion_counts"] = new_fc_history
        pkv = self.streaming_state["past_key_values"]

        # Pass all necessary information to the underlying language model.
        # The modified Qwen2Model will now correctly use `position_ids` for RoPE
        # and generate layer-specific attention masks using `layer_fusion_counts`.
        outputs = self.language_model(
            inputs_embeds=current_embeds,
            position_ids=position_ids,
            past_key_values=pkv,
            use_cache=True,
            layer_fusion_counts=new_fc_history,
            # No need to pass attention_mask, it's handled internally now
        )
        return LlavaOnevisionModelOutputWithPast(
            last_hidden_state=outputs.last_hidden_state,
            past_key_values=pkv,
            hidden_states=None,
            attentions=None,
        )

    def get_video_features(
        self,
        pixel_values: torch.FloatTensor,
        vision_feature_layer: Union[int, list[int]],
        vision_feature_select_strategy: str,
        **kwargs,  
    ):
        """
        Obtains video last hidden states from the vision tower, apply multimodal projection and pooling.
        """
        batch_size, frames, channels, height, width = pixel_values.shape
        pixel_values = pixel_values.view(
            batch_size * frames, channels, height, width)
        video_features = self.vision_tower(
            pixel_values, output_hidden_states=True)

        if isinstance(vision_feature_layer, int):
            selected_video_feature = video_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [video_features.hidden_states[layer_idx]
                       for layer_idx in vision_feature_layer]
            selected_video_feature = torch.cat(hs_pool, dim=-1)

        if vision_feature_select_strategy == "default":
            selected_video_feature = selected_video_feature[:, 1:]
        video_features = self.multi_modal_projector(selected_video_feature)

        video_features = self.apply_pooling(video_features)
        video_features = video_features.reshape(
            batch_size, frames * video_features.shape[1], -1)

        return video_features

    def apply_pooling(self, image_features):
        height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
        batch_frames, seq_len, dim = image_features.shape
        image_features = image_features.view(batch_frames, height, width, -1)
        image_features = image_features.permute(0, 3, 1, 2).contiguous()

        height, width = image_features.shape[2:]
        scaled_shape = [math.ceil(height / 2), math.ceil(width / 2)]
        image_features = nn.functional.interpolate(
            image_features, size=scaled_shape, mode="bilinear")

        image_features = image_features.permute(0, 2, 3, 1)
        image_features = image_features.view(batch_frames, -1, dim)
        return image_features


@auto_docstring(
    custom_intro="""
    The LLAVA-NeXT model which consists of a vision backbone and a language model.
    """
)
class LlavaOnevisionForConditionalGeneration(LlavaOnevisionPreTrainedModel, GenerationMixin):
    _checkpoint_conversion_mapping = {
        "^language_model.model": "model.language_model",
        "^vision_tower": "model.vision_tower",
        "^multi_modal_projector": "model.multi_modal_projector",
        "^image_newline": "model.image_newline",
        "^language_model.lm_head": "lm_head",
    }
    _tied_weights_keys = ["lm_head.weight"]

    def __init__(self, config: LlavaOnevisionConfig):
        super().__init__(config)
        self.model = LlavaOnevisionModel(config)
        self.lm_head = nn.Linear(
            config.text_config.hidden_size, config.text_config.vocab_size, bias=False)
        self.post_init()

    def get_input_embeddings(self):
        return self.model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.model.set_input_embeddings(value)

    def get_output_embeddings(self) -> nn.Module:
        return self.lm_head

    def set_decoder(self, decoder):
        self.model.set_decoder(decoder)

    def get_decoder(self):
        return self.model.get_decoder()

    def pack_image_features(self, image_features, image_sizes, vision_feature_select_strategy, image_newline=None):
        return self.model.pack_image_features(
            image_features=image_features,
            image_sizes=image_sizes,
            vision_feature_select_strategy=vision_feature_select_strategy,
            image_newline=image_newline,
        )

    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        image_sizes: torch.Tensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
    ):
        return self.model.get_image_features(
            pixel_values=pixel_values,
            image_sizes=image_sizes,
            vision_feature_layer=vision_feature_layer,
            vision_feature_select_strategy=vision_feature_select_strategy,
        )

    # Make modules available through conditional class for BC
    @property
    def language_model(self):
        return self.model.language_model

    @property
    def vision_tower(self):
        return self.model.vision_tower

    @property
    def multi_modal_projector(self):
        return self.model.multi_modal_projector

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.FloatTensor] = None,
        image_sizes: Optional[torch.LongTensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_sizes_videos: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        layer_fusion_counts: Optional[List[torch.Tensor]] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> Union[tuple, LlavaOnevisionCausalLMOutputWithPast]:
        r"""
        image_sizes_videos (`torch.LongTensor` of shape `(batch_size, frames, 2)`, *optional*):
            The sizes of the videos in the batch, being (height, width) for each frame in the video.
        vision_aspect_ratio (`str`, *optional*, defaults to `"anyres_max_9"`):
            Aspect ratio used when processong image features. The default value is "anyres_max_9".
        batch_num_images (`torch.LongTensor`, *optional*):
            Number of images in each sample.
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.

        Example:

        ```python
        >>> from PIL import Image
        >>> import requests
        >>> import torch
        >>> from transformers import LlavaOnevisionProcessor, LlavaOnevisionForConditionalGeneration

        >>> model = LlavaOnevisionForConditionalGeneration.from_pretrained("llava-hf/llava-onevision-qwen2-7b-ov-hf", dtype="float16", device_map="cuda:0")
        >>> processor = LlavaOnevisionProcessor.from_pretrained("llava-hf/llava-onevision-qwen2-7b-ov-hf")

        >>> conversation = [
        ...     {
        ...       "role": "user",
        ...       "content": [
        ...           {"type": "text", "text": "What is shown in this image?"},
        ...           {"type": "image"},
        ...         ],
        ...     },
        ... ]
        >>> prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)

        >>> image_file = "http://images.cocodataset.org/val2017/000000039769.jpg"
        >>> raw_image = Image.open(requests.get(image_file, stream=True).raw)
        >>> inputs = processor(text=prompt, images=raw_image, return_tensors='pt').to(0, torch.float16)

        >>> output = model.generate(**inputs, max_new_tokens=20, do_sample=False)
        >>> processor.batch_decode(output, skip_special_tokens=True)[0]
        "user\n\nWhat is shown in this image?\nassistant\ncat"
        ```"""
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        outputs = self.model(
            input_ids=input_ids,
            pixel_values=pixel_values,
            pixel_values_videos=pixel_values_videos,
            image_sizes=image_sizes,
            image_sizes_videos=image_sizes_videos,
            vision_aspect_ratio=vision_aspect_ratio,
            vision_feature_layer=vision_feature_layer,
            vision_feature_select_strategy=vision_feature_select_strategy,
            batch_num_images=batch_num_images,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=True,
            cache_position=cache_position,
            logits_to_keep=logits_to_keep,
            layer_fusion_counts=layer_fusion_counts,
            **kwargs,
        )

        hidden_states = outputs[0]
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep,
                              None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(
                logits=logits, labels=labels, vocab_size=self.config.text_config.vocab_size, **kwargs
            )

        return LlavaOnevisionCausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            image_hidden_states=outputs.image_hidden_states,
            video_hidden_states=outputs.video_hidden_states,
        )

    def prepare_inputs_for_generation(
        self,
        input_ids,
        past_key_values=None,
        inputs_embeds=None,
        pixel_values=None,
        image_sizes=None,
        pixel_values_videos=None,
        image_sizes_videos=None,
        attention_mask=None,
        cache_position=None,
        logits_to_keep=None,
        **kwargs,
    ):
        # Overwritten -- in specific circumstances we don't want to forward image inputs to the model

        model_inputs = super().prepare_inputs_for_generation(
            input_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            cache_position=cache_position,
            logits_to_keep=logits_to_keep,
            **kwargs,
        )
        if "layer_fusion_counts" in kwargs:
            model_inputs["layer_fusion_counts"] = kwargs["layer_fusion_counts"]

        if cache_position[0] == 0:
            # If we're in cached decoding stage, pixel values should be None because input ids do not contain special image token anymore
            # Otherwise we need pixel values to be passed to model
            model_inputs["pixel_values"] = pixel_values
            model_inputs["image_sizes"] = image_sizes
            model_inputs["pixel_values_videos"] = pixel_values_videos
            model_inputs["image_sizes_videos"] = image_sizes_videos

        return model_inputs

    @staticmethod
    def _prepare_4d_causal_attention_mask_with_cache_position(
        attention_mask: torch.Tensor,
        sequence_length: int,
        target_length: int,
        dtype: torch.dtype,
        cache_position: torch.Tensor,
        batch_size: int,
        **kwargs,
    ):
        """
        Creates a causal 4D mask of shape `(batch_size, 1, query_length, key_value_length)` from a 2D mask of shape
        `(batch_size, key_value_length)`, or if the input `attention_mask` is already 4D, do nothing.

        Args:
            attention_mask (`torch.Tensor`):
                A 2D attention mask of shape `(batch_size, key_value_length)` or a 4D attention mask of shape
                `(batch_size, 1, query_length, key_value_length)`.
            sequence_length (`int`):
                The sequence length being processed.
            target_length (`int`):
                The target length: when generating with static cache, the mask should be as long as the static cache,
                to account for the 0 padding, the part of the cache that is not filled yet.
            dtype (`torch.dtype`):
                The dtype to use for the 4D attention mask.
            cache_position (`torch.Tensor`):
                Indices depicting the position of the input sequence tokens in the sequence.
            batch_size (`torch.Tensor`):
                Batch size.
        """
        if attention_mask is not None and attention_mask.dim() == 4:
            # In this case we assume that the mask comes already in inverted form and requires no inversion or slicing.
            causal_mask = attention_mask
        else:
            min_dtype = torch.finfo(dtype).min
            causal_mask = torch.full(
                (sequence_length, target_length), fill_value=min_dtype, dtype=dtype, device=cache_position.device
            )
            if sequence_length != 1:
                causal_mask = torch.triu(causal_mask, diagonal=1)
            causal_mask *= torch.arange(
                target_length, device=cache_position.device) > cache_position.reshape(-1, 1)
            causal_mask = causal_mask[None, None,
                                      :, :].expand(batch_size, 1, -1, -1)
            if attention_mask is not None:
                causal_mask = causal_mask.clone()  # copy to contiguous memory for in-place edit
                mask_length = attention_mask.shape[-1]
                padding_mask = causal_mask[:, :, :, :mask_length] + attention_mask[:, None, None, :].to(
                    causal_mask.device
                )
                padding_mask = padding_mask == 0
                causal_mask[:, :, :, :mask_length] = causal_mask[:, :, :, :mask_length].masked_fill(
                    padding_mask, min_dtype
                )

        return causal_mask

    def get_video_features(
        self,
        pixel_values: torch.FloatTensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
    ):
        return self.model.get_video_features(
            pixel_values=pixel_values,
            vision_feature_layer=vision_feature_layer,
            vision_feature_select_strategy=vision_feature_select_strategy,
        )


__all__ = ["LlavaOnevisionModel", "LlavaOnevisionForConditionalGeneration",
           "LlavaOnevisionPreTrainedModel"]
